/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.MundialInterclubes.Aprensetação;

import br.edu.ifnmg.MudialInterclubes.Negocio.CamposObrigatoriosExceptions;
import br.edu.ifnmg.MudialInterclubes.Negocio.JogadorBO;
import br.edu.ifnmg.MudialInterclubes.Negocio.JogadorDuplicadoException;
import br.edu.ifnmg.MudialInterclubes.Negocio.TimeBO;
import br.edu.ifnmg.MudialInterclubes.Negocio.TimeCompletoException;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Wellington
 */
public class CadastroJogador extends javax.swing.JFrame {

    private Jogador jogadorEmEdicao;
    List<Time> times;
    String item = "";

    /**
     * Creates new form CadastroJogador
     */
    public CadastroJogador() throws SQLException {
        this.jogadorEmEdicao = new Jogador();
        prepararTela();
    }

    public void prepararTela() throws SQLException {
        try {
            this.initComponents();
            this.carregarComboTimes();
            this.carregarComboNumeroCamisa();
        } catch (Exception e) {
            String mensagem = "Erro inesperado! Informe a mensagem de erro ao administrador do sistema.";
            mensagem += "\nMensagem de erro:\n" + e.getMessage();
            JOptionPane.showMessageDialog(this, mensagem, "Manobras cadastrados", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }
    }
 @Override
    public void setVisible(boolean exibir) {
        super.setVisible(exibir);
        if (exibir == true) {
            try {
                this.carregarComboTimes();
            } catch (SQLException ex) {
                Logger.getLogger(CadastroJogador.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNomeJogador = new javax.swing.JTextField();
        cbxNumeroCamisa = new javax.swing.JComboBox<>();
        lblNome = new javax.swing.JLabel();
        lblNomeTime = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblNumeoCamisa = new javax.swing.JLabel();
        cbxTimes = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jogador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 2, 18))); // NOI18N

        lblNome.setText("Nome:");

        lblNomeTime.setText("Time:");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblNumeoCamisa.setText("Numero camisa:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomeJogador, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 192, Short.MAX_VALUE)
                        .addComponent(btnSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomeTime)
                            .addComponent(lblNome)
                            .addComponent(cbxNumeroCamisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumeoCamisa)
                            .addComponent(cbxTimes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNome)
                .addGap(14, 14, 14)
                .addComponent(txtNomeJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNomeTime)
                .addGap(18, 18, 18)
                .addComponent(cbxTimes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(lblNumeoCamisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(cbxNumeroCamisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalvar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            this.incluirJogador();
        } catch (SQLException ex) {
            Logger.getLogger(CadastroJogador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbxNumeroCamisa;
    private javax.swing.JComboBox<String> cbxTimes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeTime;
    private javax.swing.JLabel lblNumeoCamisa;
    private javax.swing.JTextField txtNomeJogador;
    // End of variables declaration//GEN-END:variables

    private void carregarComboNumeroCamisa() {
        this.cbxNumeroCamisa.removeAllItems();
        this.cbxNumeroCamisa.addItem("");
        for (int x = 0; x < 23; x++) {
            this.cbxNumeroCamisa.addItem(Integer.toString(x + 1));
        }
    }

    private void carregarComboTimes() throws SQLException {
        TimeBO timeBO = new TimeBO();
        this.times = timeBO.buscarTodosTimes();
        cbxTimes.removeAllItems();
        this.cbxTimes.addItem("");
        for (Time t : times) {
            cbxTimes.addItem(t.getNome());
        }
    }

    private void incluirJogador() throws SQLException {
        try {
            this.recuperarCamposTela();           
            JogadorBO jogadorBO = new JogadorBO();
            jogadorBO.incluirJogador(jogadorEmEdicao);
            JOptionPane.showMessageDialog(this, "Jogador incluido com sucesso!", "Novo jogador", JOptionPane.INFORMATION_MESSAGE);            
        } catch (CamposObrigatoriosExceptions c) {
            String mensagem = "Aviso!\n" + c.getMessage();
            JOptionPane.showMessageDialog(this, mensagem, "Novo jogadore", JOptionPane.INFORMATION_MESSAGE);
        } catch (JogadorDuplicadoException j) {
            String mensagem = "Aviso!\n" + j.getMessage();
            JOptionPane.showMessageDialog(this, mensagem, "Novo jogador", JOptionPane.INFORMATION_MESSAGE);
        }catch (TimeCompletoException t) {
            String mensagem = "Aviso!\n" + t.getMessage();
            JOptionPane.showMessageDialog(this, mensagem, "Novo jogador", JOptionPane.INFORMATION_MESSAGE);

        }

    }

    private void recuperarCamposTela() {
       
         String numero = (String) cbxNumeroCamisa.getSelectedItem();
         
        this.jogadorEmEdicao.setNumeroCamisa(Integer.parseInt(numero)); 
        this.jogadorEmEdicao.setNome(txtNomeJogador.getText());
        this.item = (String) cbxTimes.getSelectedItem();
        for (Time t : times){
            if (t.getNome().equals(item)) {
                this.jogadorEmEdicao.setIdTime(t.getId());
            }
        }
         
    }   
}
